apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-autoatendimento
  name: app-autoatendimento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-autoatendimento
  template:
    metadata:
      labels:
        app: app-autoatendimento
    spec:
      containers:
        - image: rafaelbgil/fiap-pos-tech:v11
          name: fiap-pos-tech
          env:
            - name: DATABASE_HOST
              value: banco-service
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: FIAP-LANCHONETE
            - name: DATABASE_USER
              value: fiap-user
            - name: DATABASE_PASSWORD
              value: fiap-password
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 400m        
              
          livenessProbe:
            httpGet:
              path: '/admin/login/?next=/admin/'
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

        - name: proxy-reverso
          image: rafaelbgil/fiap-pos-tech-proxy:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 400m   
           
          volumeMounts:
            - name: nginx-app-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: '/static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js'
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

      volumes:
        - name: nginx-app-conf
          configMap:
            name: nginx-app-conf
