apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: banco
  name: banco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco
  template:
    metadata:
      labels:
        app: banco
    spec:
      containers:
        - image: mariadb:11.1
          name: mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_USER
              value: fiap-user
            - name: MARIADB_PASSWORD
              value: fiap-password
            - name: MARIADB_DATABASE
              value: FIAP-LANCHONETE
            - name: MARIADB_ROOT_PASSWORD
              value: fiap-password
