# Generated by Django 4.2.1 on 2023-10-17 21:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nome', models.CharField(help_text='Informe o nome do cliente, evite o uso de caracteres especiais.', max_length=120, verbose_name='Nome completo do cliente')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('cpf', models.CharField(editable=False, max_length=11, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricacao', models.CharField(max_length=1024, null=True)),
                ('preco', models.FloatField()),
                ('imagem_url', models.CharField(max_length=1024, null=True)),
                ('categoria', models.CharField(max_length=40, null=True)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=1024, null=True)),
                ('preco', models.FloatField()),
                ('imagem_url', models.CharField(max_length=1024, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
    ]
