# Generated by Django 4.2.1 on 2023-10-11 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nome', models.CharField(help_text='Informe o nome do cliente, evite o uso de caracteres especiais.', max_length=120, verbose_name='Nome completo do cliente')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('cpf', models.CharField(editable=False, max_length=11, null=True, unique=True)),
            ],
        ),
    ]
