# Generated by Django 4.2.1 on 2023-10-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(editable=False, max_length=11, null=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('valor', models.FloatField()),
                ('status', models.CharField(choices=[('aguardando_pagamento', 'aguardando_pagamento'), ('preparando', 'preparando'), ('pronto', 'pronto'), ('entregue', 'entregue'), ('cancelado', 'cancelado')], default='aguardando_pagamento', max_length=40)),
            ],
        ),
    ]
