# Generated by Django 4.2.1 on 2023-10-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pedido_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
