# Generated by Django 4.2.1 on 2023-10-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cliente_uuid_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Informe o nome do cliente, evite o uso de caracteres especiais.', max_length=120, verbose_name='Nome completo do cliente'),
        ),
    ]
