# Generated by Django 4.2.1 on 2023-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pedido_cpf_alter_pedido_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
