# Generated by Django 4.2.1 on 2023-10-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pedido_cpf_alter_pedido_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pedido'),
            preserve_default=False,
        ),
    ]
