# Generated by Django 4.2.1 on 2023-10-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_produtopedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtopedido',
            name='categoria',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='descricacao',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
