# Generated by Django 4.2.1 on 2023-10-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_produtopedido_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoPedido',
            new_name='ItemPedido',
        ),
    ]
