openapi: 3.0.3
info:
  title: Api Autoatendimento Lanchonete
  version: 1.0.0
  description: Api de Autoatendimento de lanchones - Fiap Pos-tech
paths:
  /api/categoria/:
    get:
      operationId: categoria_list
      description: Api para inclusao de algo
      tags:
      - categoria
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categoria'
          description: ''
    post:
      operationId: categoria_create
      tags:
      - categoria
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categoria'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Categoria'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Categoria'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
          description: ''
  /api/cliente/:
    get:
      operationId: cliente_list
      description: Visualiza os usuarios cadastrados
      tags:
      - cliente
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
          description: ''
    post:
      operationId: cliente_create
      description: Cadastra novo usuario
      tags:
      - cliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Cliente'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
          description: ''
  /api/cliente/{uuid}/:
    get:
      operationId: cliente_retrieve
      description: Visualiza de usuario selecionado pelo {uuid}
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - cliente
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Categoria:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 40
      required:
      - id
      - nome
    Cliente:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        uuid:
          type: string
          readOnly: true
          maxLength: 32
        nome:
          type: string
          maxLength: 120
        email:
          type: string
          maxLength: 120
      required:
      - email
      - id
      - nome
      - uuid
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
